export * from './heroSection'
export * from './reviewsSection'
export * from './avsVideoMaker.styled'
export * from './specsSection'
export * from './makeYourVideoSection'
export * from './powerSection'
export * from './getStartedSection'
export * from './stepsSection'
